### ISSUE TITLE
Infoview doesn't work with Docker

### ISSUE THREAD

**Issue by arh4uwe** [leanprover/vscode-lean#208]
My group uses a virtual machine called Docker when working on our projects. Basically, Docker creates a container to which VS Code can attach.

The issue is that while the Infoview panel works fine when the container is running, it goes completely blank when VS Code is attached to a Docker container. This issue didn't happen at all back when Lean Infoview was Lean Goal, so I think downgrading Lean, this plugin, or VS Code might be a temporary solution. How would I go about doing that?

**Comment by bryangingechen** [comment]
You could try the [.vsix package](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix) here: https://github.com/leanprover/vscode-lean/releases/tag/v0.15.15

**Comment by bryangingechen** [comment]
[Related discussion on Zulip](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/vscode.20infoview.20overhaul/near/203024285) (re: SSH-remote VS Code.)

**Comment by arh4uwe** [comment]
Downgrading to an earlier version (0.15.15) made the issue go away. Hopefully Lean Infoview gets fixed in a later update. Until then, 0.15.15 will work for me.

**Comment by sjkillen** [comment]
This is still an issue in 0.16.5 using a vscode remote container
Installing the .vsix @ 0.15.15 works for now
Note that the suggested method of .vsix install:
`code --install-extension myextension.vsix`
Does not work in vscode remote. Must install from GUI in extensions tab

**Comment by bryangingechen** [comment]
Yeah, sadly I haven't had any time to look further into this at all. Feel free to post here or on Zulip if you have any ideas as to how we can get this working again.

**Comment by sjkillen** [comment]
The culprit seems to be seems to be getMediaPath from infoview.ts:346
Currently this function is
```ts
private getMediaPath(mediaFile: string): string {
        // workaround for https://github.com/microsoft/vscode/issues/89038
        return this.staticServer.mkUri(join(this.context.extensionPath, 'media', mediaFile));
}
```
If I change it back to what it was in 0.15.5
```ts
private getMediaPath(mediaFile: string): string {
        // workaround for https://github.com/microsoft/vscode/issues/89038
        return Uri.file(this.context.asAbsolutePath(join('media', mediaFile)))
            .with({scheme: 'vscode-resource'}).toString();
}
```
The extension works in vscode docker
Reproduction:
build vsix with above change
clone https://github.com/sjkillen/example, open in container and install vsix

**Comment by bryangingechen** [comment]
Awesome! @gebner I guess we can revert all these fixes now as https://github.com/microsoft/vscode/issues/89038 seems to be fixed. I'll make a PR in a few hours (unless someone beats me to it).
